//! Task executor — runs steps generated by the planner.

use tauri::{AppHandle, Manager, Emitter};
use uuid::Uuid;
use std::time::Duration;

use crate::error::CntrlError;
use crate::services::browser::BrowserService;
use crate::services::planner::{Step, TaskStatus, TaskResult};

/// Execute a sequence of steps.
pub async fn execute_steps(
    app: &AppHandle,
    task_id: Uuid,
    steps: Vec<Step>,
) -> Result<TaskResult, CntrlError> {
    let browser = app.state::<BrowserService>();
    
    // We'll get the active tab to run commands against
    // (In a real implementation, we might need to find the active tab ID first)
    // For now, we'll just get the first tab or create one if none exist.
    let mut active_tab_id = None;
    if let Ok(tabs) = browser.get_tabs() {
        if !tabs.is_empty() {
            // Just use the first one for simplicity in this phase
            active_tab_id = Some(tabs[0].id.clone());
        }
    }
    
    for (idx, step) in steps.iter().enumerate() {
        // Emit progress event
        let _ = app.emit("task-progress", (task_id, idx, step.clone()));
        
        match step {
            Step::NavigateTo(url) => {
                if let Some(ref id) = active_tab_id {
                    browser.navigate(app, id.clone(), url.clone())?;
                } else {
                    active_tab_id = Some(browser.open_tab(app, url.clone(), false)?);
                }
            }
            Step::WaitFor(ms) => {
                tokio::time::sleep(Duration::from_millis(*ms)).await;
            }
            Step::ReportResult(_msg) => {
                // Just log or handle in the frontend
            }
            Step::RunScript(_js) => {
                if let Some(ref _id) = active_tab_id {
                    // dummy for now since eval isn't on BrowserService yet
                }
            }
            Step::ReadPage => {
                // Dummy for now
            }
            _ => {
                // Other steps not fully implemented yet
            }
        }
    }
    
    // Emit completion
    let _ = app.emit("task-completed", task_id);
    
    Ok(TaskResult {
        task_id,
        status: TaskStatus::Done,
        steps,
        failed_at: None,
        message: "Task completed successfully".to_string(),
        data: None,
    })
}
